name 'yaas-dev'
version '1.0.0'

author 'jeromebridge'
license 'Apache License, Version 2.0'
project_page 'http://github.com/maestrodev/puppet-sonarqube'
source 'http://github.com/maestrodev/puppet-sonarqube'
summary 'SonarQube installation and configuration'
description 'A module to install and configure SonarQube (former Sonar)'

